/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.shop;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;

/**
 *
 * @author RAUSHAN
 */
public class Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_availability = new javax.swing.JButton();
        b_sell = new javax.swing.JButton();
        b_order = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b_vorder = new javax.swing.JButton();
        b_stock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setBounds(new java.awt.Rectangle(300, 200, 500, 500));
        setName("mainmenu"); // NOI18N

        b_availability.setText("SEARCH AVAILABILITY");
        b_availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_availabilityActionPerformed(evt);
            }
        });
        b_availability.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_availabilityKeyPressed(evt);
            }
        });

        b_sell.setText("SELL PRODUCT");
        b_sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sellActionPerformed(evt);
            }
        });

        b_order.setText("PLACE ORDER");
        b_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_orderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("          MAIN MENU");

        b_vorder.setText("VIEW ORDER");
        b_vorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_vorderActionPerformed(evt);
            }
        });

        b_stock.setText("Update Stock");
        b_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_order, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b_availability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_sell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_vorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(b_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_sell, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_order, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_vorder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_availabilityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_availabilityKeyPressed
        if(evt.isAltDown() && evt.getKeyCode()==KeyEvent.VK_S)
        {
            JOptionPane.showMessageDialog(null,"Alt key pressed");
            
        }
          
            
    }//GEN-LAST:event_b_availabilityKeyPressed

    private void b_availabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_availabilityActionPerformed
       Availability obj=new Availability();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_b_availabilityActionPerformed

    private void b_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_orderActionPerformed
        new Placeorder().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_orderActionPerformed

    private void b_sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sellActionPerformed
       new sell().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_b_sellActionPerformed

    private void b_vorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_vorderActionPerformed
         try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/msas","root","Bi2i@1234");
            String query="select * from orders";
            PreparedStatement s=con.prepareStatement(query);
            
            s.executeQuery();
           
            ResultSet rs=s.getResultSet();
            ResultSetMetaData rm=rs.getMetaData();
            int columncount=rm.getColumnCount();
            
            String str="";
            for(int i=1;i<=columncount;i++)
            {
                
                str+=rm.getColumnName(i) +"\t";            
            }
        
           
        while(rs.next())
        {
            //str+="\n"+rm.getTableName(1)+"\t";
            str+="\n" + rs.getString(1)+"\t";
            str+=rs.getString(2)+"\t";
            str+=rs.getInt(3);
          
        }
        System.out.println(str);
        searchresult obj=new searchresult();
        obj.setVisible(true);
        obj.setresult(str);
        this.dispose();
        s.close();
        con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_b_vorderActionPerformed

    private void b_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_stockActionPerformed

        new update().setVisible(true);
        dispose();
    }//GEN-LAST:event_b_stockActionPerformed

    /**arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b_availability;
    public javax.swing.JButton b_order;
    public javax.swing.JButton b_sell;
    public javax.swing.JButton b_stock;
    public javax.swing.JButton b_vorder;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
