/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.shop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RAUSHAN
 */
public class sell extends javax.swing.JFrame {

    /**
     * Creates new form sell
     */
    public sell() {
        initComponents();
    }

                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_brand = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb_model = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tf_imei = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_quantity = new javax.swing.JTextField();
        b_submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("       Sell ");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setText("Brand :- ");

        cb_brand.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cb_brand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<Select >>", "Samsung", "Nokia", "Micromax", "Apple", "Blackberry", "LG", "htc", "Sony Erricson", "Karbon" }));
        cb_brand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_brandItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("Model :- ");

        cb_model.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cb_model.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<<select>>" }));
        cb_model.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_modelItemStateChanged(evt);
            }
        });
        cb_model.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_modelFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("IMEI :- ");

        tf_imei.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        tf_imei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_imeiFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setText("Price :- ");

        tf_price.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setText("Quantity :- ");

        tf_quantity.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        b_submit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b_submit.setText("SUBMIT");
        b_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setText("Date :-");

        tf_date.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_brand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_model, 0, 202, Short.MAX_VALUE)
                            .addComponent(tf_imei)
                            .addComponent(tf_price)
                            .addComponent(tf_quantity)
                            .addComponent(tf_date)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(b_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_model, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_imei)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_price))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_quantity)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_date)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addComponent(b_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_modelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_modelItemStateChanged
        /* try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobileshop","root","meenu");
             
            String str=cb_model.getSelectedItem().toString();
            
            String query="select price from samsung where model= ?";
            PreparedStatement s=con.prepareStatement(query);
            s.setString(1,str);
            ResultSet rs=s.getResultSet();
            //cb_model.setEnabled(true);
            while(rs.next())
            {
                tf_price.setText(""+rs.getInt(1));
            }
            s.close();
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cb_modelItemStateChanged

    private void cb_brandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_brandItemStateChanged
        try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/msas","root","Bi2i@1234");
            Statement s=con.createStatement();
            s.executeQuery("select model from samsung");
            ResultSet rs=s.getResultSet();
            cb_model.setEnabled(true);
            if(cb_brand.getSelectedItem().equals("Samsung"))
            {
            while(rs.next())
            {
                cb_model.addItem(rs.getString(1));
            }
            }
            else
            {
                cb_model.removeAllItems();
                cb_model.addItem("<<select>>");
            }
            s.close();
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_brandItemStateChanged

    private void cb_modelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_modelFocusLost
        /*try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobileshop","root","meenu");
             
            String str=cb_model.getSelectedItem().toString();
            
            String query="select price from samsung where model= ?";
            PreparedStatement s=con.prepareStatement(query);
            s.setString(1,str);
            ResultSet rs=s.getResultSet();
            //cb_model.setEnabled(true);
            while(rs.next())
            {
                tf_price.setText(""+rs.getInt(1));
            }
            s.close();
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_cb_modelFocusLost

    private void tf_imeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_imeiFocusLost
         try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/msas","root","Bi2i@1234");
             
            String str=cb_model.getSelectedItem().toString();
            
            String query="select price from samsung where model=?";
            PreparedStatement s=con.prepareStatement(query);
           
            s.setString(1,str);
             s.executeQuery();
            ResultSet rs=s.getResultSet();
            //cb_model.setEnabled(true);
            rs.next();
            tf_price.setText(""+rs.getInt(1));
            
            s.close();
            con.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tf_imeiFocusLost

    private void b_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submitActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");//to load driver
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/msas","root","Bi2i@1234");
            String query="insert into sales values(?,?,?,?,?,?)";
            PreparedStatement s=con.prepareStatement(query);
            s.setString(1,cb_brand.getSelectedItem().toString());
            s.setString(2,cb_model.getSelectedItem().toString());
            s.setString(3,tf_imei.getText());
            s.setInt(4,Integer.parseInt(tf_price.getText()));
            s.setInt(5,Integer.parseInt(tf_quantity.getText()));
            s.setString(6,tf_date.getText());
            s.execute();
            int price=Integer.parseInt(tf_price.getText());
            int quan=Integer.parseInt(tf_quantity.getText());
            JOptionPane.showMessageDialog(null, "Bill Amount = " + (price*quan));
            new Mainmenu().setVisible(true);
            this.dispose();
            s.close();
            con.close();
        }   
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_b_submitActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_submit;
    private javax.swing.JComboBox cb_brand;
    private javax.swing.JComboBox cb_model;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_imei;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_quantity;
    // End of variables declaration//GEN-END:variables
}
